name: Qodana - Code Inspection Example

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Qodana - Code Inspection
        uses:  tiulpin/qodana-action@main
        with:
          baseline-path: ".github/workflows/baseline-short.sarif.json"
          baseline-include-absent: true
          fail-threshold: 1
