name: Qodana - Status check
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Qodana - Code Inspection
        uses:  tiulpin/qodana-action@main
        with:
          baseline-path: ".github/workflows/baseline-short.sarif.json"
          baseline-include-absent: true
          fail-threshold: 1
          
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Qodana failed
          conclusion: ${{ job.status }}
          output: |
            {"summary":${{ steps.test.outputs.summary }}}
